#include<stdio.h>
#include<conio.h>
int main()
{

 int week;
 clrscr();
 printf("enter the week day:");
 scanf("%d",&week);
 if(week==1)
 printf(" Sunday");

 else if(week==2)
 printf(" Monday");
 else if(week==3)
 printf(" day");

 else if(week==3)
 printf(" tuesday");

 else if(week==4)
 printf(" Wednesday");

else if(week==5)
 printf(" thursday");

 else if(week==6)
 printf("Friday");

 else if(week==7)
 printf("Saturday");
 getch();
 }